all:
	pdflatex CC-2015-TP2-CamposinhosAntunesOliveira.tex
	bibtex CC-2015-TP2-CamposinhosAntunesOliveira
	pdflatex CC-2015-TP2-CamposinhosAntunesOliveira
	pdflatex CC-2015-TP2-CamposinhosAntunesOliveira

clean:

	rm *.aux *.log *.out *.toc *.bbl *.blg *~ *xml *backup *blx*

